export const users = [
	{
		userName: "admin",
		id: "admin",
		name: "admin",
		password: "adminadmin",
		email: "admin@example.com",
	},
	{
		userName: "juanPerez",
		id: "u1",
		name: "Juan",
		password: "Juan123!",
		email: "juan.perez@example.com",
	},
	{
		userName: "johnDoe",
		id: "u2",
		name: "John",
		password: "DoeJohn2025#",
		email: "john.doe@example.com",
	},
	{
		userName: "luisGonzalez",
		id: "u3",
		name: "Luis",
		password: "Luis#456",
		email: "luis.gonzalez@example.com",
	},
	{
		userName: "lauraMtz",
		id: "u4",
		name: "Laura",
		password: "Laura!789",
		email: "laura.mtz@example.com",
	},
	{
		userName: "raquelSanchez",
		id: "u5",
		name: "Raquel",
		password: "RaquelSecure1$",
		email: "raquel.sanchez@example.com",
	},
	{
		userName: "marioLopez",
		id: "u6",
		name: "Mario",
		password: "Mario2025*",
		email: "mario.lopez@example.com",
	},
	{
		userName: "javiCordoba",
		id: "u7",
		name: "Javi",
		password: "JaviPass#7",
		email: "javi.cordoba@example.com",
	},
	{
		userName: "ferDiaz",
		id: "u8",
		name: "Fer",
		password: "Fer!321",
		email: "fer.diaz@example.com",
	},
];
